load:
  czi_path: TB_sample/extern_Synlab_2156_17_3_MTB.czi 
  tile: 672 # None if whole smear, otherwise number of tile

preprocessing:
  algorithm: sharp

thresholding:
  algorithm: otsu #otsu, hard, adaptive, gaussian  (only otsu is supported for now)
  hard_threshold_param: 5000 # only used if thresholding_algorithm is hard
  block_size: 10 # only for adaptive (not sure what it is)
  c: 10 #only for adaptive (not sure what it is)
  split: True  # whether to split the image into tiles or not before applying thresholding algorithm 
  tile_size: 16 # size of single tiles if split is True

postprocessing:
  number_of_black_pixels: 215 # number of black pixels to decide whether a tile is background or not


visualization:
  show: True # whether to show the image or not
  save: True # whether to save the image or not
  save_path: extern_Synlab_2156_17_3_MTB.png # path to save the image to