load:
  czi_path: TB_sample/extern_Synlab_2156_17_3_MTB.czi
  tile: None # None if whole smear, otherwise number of tile
  blurry_deselection: True # whether to remove blurry tiles or not
  interactive_config: True # whether to use interactive config or not

preprocessing:
  algorithm: sharp #sharp, rescale

thresholding:
  algorithm: adaptive_gaussian #otsu, hard, adaptive_gaussian, adaptive_mean
  hard_threshold_param: 5000 # only used 
  block_size: 25 # only for adaptive (the size of the neighborhood)
  c: -7 #only for adaptive (constant to substract from the mean)
  split: True    # whether to split the image into tiles or not 
  # before applying thresholding algorithm 
  tile_size: 16 # size of single tiles if split is True
  x_tiles: 128
  y_tiles: 94

postprocessing:
  algorithm: adaptive_gaussian #otsu, hard, adaptive_gaussian, adaptive_mean
  number_of_black_pixels: 215 # number of black pixels to decide whether a tile is background or not
  x_tiles: 128
  y_tiles: 94
  tile_size: 16 # size of single tiles if split is True
  crop: True # whether to crop the image or not

labelling_dataset: 
  create_dataset: False

saving: 
  save: False # whether to save the labelled by hand dataset or not

inference:
  do_inference: True # whether to do inference or not

visualization:
  show: True # whether to show the image or notgit 