load: 
  data_path: ['labelled_data/tile_673_smear_2156_17_3.pkl', 'labelled_data/tile_674_smear_2156_17_3.pkl', labelled_data/tile_675_smear_2156_17_3.pkl]

train:
  batch_size: 5
  epochs: 3000
  type: mlp # conv or mlp